name = "http-axios"
language = "typescript"
type = "component"
version = "0.1.0"

[component]
wit_world = "component"
wasm_target = "wasm32-wasip2"

build_command = "npm run install-and-build"
build_artifact = "dist/http-axios.wasm"
destination = "build/http_axios_s.wasm"